import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signOut } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import { getFirestore,collection,doc,setDoc,getDoc,getDocs,query,where,orderBy,serverTimestamp,writeBatch } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
import { firebaseConfig, APP_BASE_PATH } from "./firebase-config.js";

const __redirect = new URLSearchParams(location.search).get("redirect");
if (__redirect) history.replaceState({}, "", __redirect);

const fbApp=initializeApp(firebaseConfig),auth=getAuth(fbApp),db=getFirestore(fbApp),$=id=>document.getElementById(id);
let currentNovel=null,chapters=[],activeChapterId=null,proofMode=false,saveTimer=null;
const defaultPage={preset:"A6",fontSize:10.5,charsPerLine:40,linesPerPage:16,realPageMode:false};
const defaultDisplay={fontSize:16};
const defaultRules=[{from:"出来る",to:"できる"},{from:"下さい",to:"ください"},{from:"致します",to:"いたします"},{from:"と言う",to:"という"},{from:"事",to:"こと"},{from:"様な",to:"ような"}];
function showView(id){["authView","dashboardView","editorView"].forEach(v=>$(v).classList.toggle("hidden",v!==id));}
function toast(m){$("toast").textContent=m;$("toast").classList.remove("hidden");setTimeout(()=>$("toast").classList.add("hidden"),2200)}
function loginEmail(id){const c=id.trim().toLowerCase().replace(/[^a-z0-9._-]/g,"-");if(!c)throw Error("ログインIDを入力してください。");return `${c}@novel.local`;}
function basePath(){let b=APP_BASE_PATH||"/";if(!b.startsWith("/"))b="/"+b;if(!b.endsWith("/"))b+="/";return b;}
function pathForSlug(s){return `${basePath()}write/${encodeURIComponent(s)}`;}
function routeSlug(){let p=decodeURIComponent(location.pathname),b=basePath();if(p.startsWith(b))p=p.slice(b.length);let m=p.match(/^write\/([^/]+)/);return m?m[1]:null;}
function slugifyLatin(s){return s.toLowerCase().trim().replace(/[’'\"]/g,"").replace(/&/g,"-and-").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").replace(/-+/g,"-");}
const kana={"きゃ":"kya","きゅ":"kyu","きょ":"kyo","しゃ":"sha","しゅ":"shu","しょ":"sho","ちゃ":"cha","ちゅ":"chu","ちょ":"cho","にゃ":"nya","にゅ":"nyu","にょ":"nyo","ひゃ":"hya","ひゅ":"hyu","ひょ":"hyo","みゃ":"mya","みゅ":"myu","みょ":"myo","りゃ":"rya","りゅ":"ryu","りょ":"ryo","ぎゃ":"gya","ぎゅ":"gyu","ぎょ":"gyo","じゃ":"ja","じゅ":"ju","じょ":"jo","びゃ":"bya","びゅ":"byu","びょ":"byo","ぴゃ":"pya","ぴゅ":"pyu","ぴょ":"pyo","あ":"a","い":"i","う":"u","え":"e","お":"o","か":"ka","き":"ki","く":"ku","け":"ke","こ":"ko","さ":"sa","し":"shi","す":"su","せ":"se","そ":"so","た":"ta","ち":"chi","つ":"tsu","て":"te","と":"to","な":"na","に":"ni","ぬ":"nu","ね":"ne","の":"no","は":"ha","ひ":"hi","ふ":"fu","へ":"he","ほ":"ho","ま":"ma","み":"mi","む":"mu","め":"me","も":"mo","や":"ya","ゆ":"yu","よ":"yo","ら":"ra","り":"ri","る":"ru","れ":"re","ろ":"ro","わ":"wa","を":"o","ん":"n","が":"ga","ぎ":"gi","ぐ":"gu","げ":"ge","ご":"go","ざ":"za","じ":"ji","ず":"zu","ぜ":"ze","ぞ":"zo","だ":"da","ぢ":"ji","づ":"zu","で":"de","ど":"do","ば":"ba","び":"bi","ぶ":"bu","べ":"be","ぼ":"bo","ぱ":"pa","ぴ":"pi","ぷ":"pu","ぺ":"pe","ぽ":"po","ー":"-"};
function kata2hira(s){return s.replace(/[\u30a1-\u30f6]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));}
function kana2romaji(s){s=kata2hira(s.trim());let o="",g=false;for(let i=0;i<s.length;i++){if(s[i]==="っ"){g=true;continue}let pair=s.slice(i,i+2),r=kana[pair];if(r)i++;else r=kana[s[i]]||(/\s/.test(s[i])?"-":"");if(g&&r){r=r[0]+r;g=false}o+=r}return slugifyLatin(o)}
function suggestSlug(){const src=$("newReading").value.trim()||$("newTitle").value.trim(),k=kana2romaji(src),l=slugifyLatin(src);$("newSlug").value=k||l||`work-${new Date().toISOString().slice(0,10).replaceAll("-","")}`;}

async function signup(){try{const id=$("loginId").value.trim(),pw=$("loginPassword").value;if(pw.length<6)throw Error("パスワードは6文字以上にしてください。");const c=await createUserWithEmailAndPassword(auth,loginEmail(id),pw);await setDoc(doc(db,"users",c.user.uid),{loginId:id,createdAt:serverTimestamp()});toast("ユーザーを作成しました。")}catch(e){toast(e.message)}}
async function login(){try{await signInWithEmailAndPassword(auth,loginEmail($("loginId").value),$("loginPassword").value)}catch{toast("ログインできませんでした。IDまたはパスワードを確認してください。")}}
async function userLabel(u){const s=await getDoc(doc(db,"users",u.uid));$("currentUserLabel").textContent=s.exists()?` / ${s.data().loginId}`:"";}
async function listNovels(){const q=query(collection(db,"novels"),where("ownerId","==",auth.currentUser.uid)),s=await getDocs(q),box=$("novelList");box.innerHTML="";if(s.empty){box.innerHTML='<p class="muted">まだ作品がありません。</p>';return}const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>((b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0)));rows.forEach(n=>{const el=document.createElement("div");el.className="novel-card";el.innerHTML='<h3></h3><div class="slug"></div><p class="muted small"></p>';el.querySelector("h3").textContent=n.title;el.querySelector(".slug").textContent=`/write/${n.slug}`;el.querySelector("p").textContent=`${(n.targetWords||80000).toLocaleString()}字`;el.onclick=()=>openNovelId(n.id,n.slug);box.appendChild(el)})}
async function dashboard(){currentNovel=null;chapters=[];activeChapterId=null;showView("dashboardView");if(location.pathname!==basePath())history.replaceState({},"",basePath());await listNovels()}
async function createNovel(){try{const title=$("newTitle").value.trim(),slug=slugifyLatin($("newSlug").value);if(!title)throw Error("作品名を入力してください。");if(!slug)throw Error("URL名を入力してください。");const uid=auth.currentUser.uid,sr=doc(db,"slugs",`${uid}_${slug}`);if((await getDoc(sr)).exists())throw Error("同じURL名の作品があります。");const nr=doc(collection(db,"novels")),cr=doc(collection(db,"novels",nr.id,"chapters")),b=writeBatch(db);b.set(nr,{ownerId:uid,title,slug,targetWords:Number($("newTarget").value)||80000,deadlines:{early:$("newEarly").value,standard:$("newStandard").value,express:$("newExpress").value},activeDeadline:"early",page:{...defaultPage},editorDisplay:{...defaultDisplay},customRules:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});b.set(cr,{title:"第1章",order:0,text:"",updatedAt:serverTimestamp()});b.set(sr,{ownerId:uid,novelId:nr.id,slug,createdAt:serverTimestamp()});await b.commit();$("newNovelDialog").close();await openNovelId(nr.id,slug)}catch(e){toast(e.message)}}
async function openNovelSlug(slug){const s=await getDoc(doc(db,"slugs",`${auth.currentUser.uid}_${slug}`));if(!s.exists()){toast("この作品を開けません。");return dashboard()}return openNovelId(s.data().novelId,slug,false)}
async function openNovelId(id,slug,push=true){const s=await getDoc(doc(db,"novels",id));if(!s.exists())return toast("作品が見つかりません。");currentNovel={id,...s.data()};currentNovel.page={...defaultPage,...(currentNovel.page||{})};currentNovel.editorDisplay={...defaultDisplay,...(currentNovel.editorDisplay||{})};currentNovel.customRules=currentNovel.customRules||[];const cs=await getDocs(query(collection(db,"novels",id,"chapters"),orderBy("order","asc")));chapters=cs.docs.map(d=>({id:d.id,...d.data()}));activeChapterId=chapters[0]?.id||null;if(push)history.pushState({},"",pathForSlug(slug));renderEditorView()}
function activeChapter(){return chapters.find(c=>c.id===activeChapterId)}
function flushEditor(){if(currentNovel&&activeChapter())activeChapter().text=$("editor").innerText.replace(/\u00a0/g," ");shadowSave()}
function shadowSave(){if(!currentNovel)return;localStorage.setItem(`novelShadow_${auth.currentUser.uid}_${currentNovel.id}`,JSON.stringify({savedAt:Date.now(),chapters}))}
function renderEditorView(){showView("editorView");$("novelTitleLabel").textContent=currentNovel.title;$("editor").style.fontSize=`${currentNovel.editorDisplay.fontSize}px`;renderTabs();renderChapter();refreshStats();countdown()}
function renderTabs(){const box=$("chapterTabs");box.innerHTML="";chapters.forEach(ch=>{const b=document.createElement("button");b.className="chapter-tab"+(ch.id===activeChapterId?" active":"");b.textContent=ch.title;b.onclick=()=>{flushEditor();activeChapterId=ch.id;renderTabs();renderChapter()};b.ondblclick=()=>{const x=prompt("章見出し",ch.title);if(x&&x.trim()){ch.title=x.trim();renderTabs();scheduleSave()}};box.appendChild(b)})}
function renderChapter(){proofMode=false;$("proofSummary").classList.add("hidden");$("editor").textContent=activeChapter()?.text||""}
async function addChapter(){flushEditor();const r=doc(collection(db,"novels",currentNovel.id,"chapters")),ch={id:r.id,title:`第${chapters.length+1}章`,order:chapters.length,text:""};chapters.push(ch);activeChapterId=ch.id;await setDoc(r,{title:ch.title,order:ch.order,text:"",updatedAt:serverTimestamp()});renderTabs();renderChapter();scheduleSave();$("editor").focus()}
function countChars(t){return(t||"").replace(/\r?\n/g,"").length}function totalChars(){flushEditor();return chapters.reduce((s,c)=>s+countChars(c.text),0)}
function pages(){const p=currentNovel.page;if(!p.realPageMode)return totalChars()/(p.charsPerLine*p.linesPerPage);let lines=0;chapters.forEach(c=>(c.text||"").split(/\r?\n/).forEach(r=>lines+=Math.max(1,Math.ceil(r.length/p.charsPerLine))));return lines/p.linesPerPage}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function todayDelta(cur){const k=`daily_${auth.currentUser.uid}_${currentNovel.id}_${todayKey()}`;if(localStorage.getItem(k)==null)localStorage.setItem(k,String(cur));return cur-Number(localStorage.getItem(k)||0)}
function remainDays(){const r=currentNovel.deadlines?.[currentNovel.activeDeadline];return r?Math.max((new Date(r)-Date.now())/86400000,0):null}
function refreshStats(){if(!currentNovel)return;const cur=totalChars(),target=Number(currentNovel.targetWords)||1,rem=Math.max(target-cur,0),pct=Math.min(cur/target*100,100),d=remainDays(),pace=d&&d>0?Math.ceil(rem/Math.max(d,1/24)):0,td=todayDelta(cur);$("wordCount").textContent=cur.toLocaleString();$("targetCount").textContent=target.toLocaleString();$("progressPct").textContent=pct.toFixed(1)+"%";$("progressBar").style.width=pct+"%";$("remainingCount").textContent=`残り${rem.toLocaleString()}字`;$("pageEstimate").textContent=`約${pages().toFixed(1)}p`;$("todayCount").textContent=`今日 ${td>=0?"+":""}${td.toLocaleString()}字`;$("paceCount").textContent=`必要 ${pace.toLocaleString()}字/日`;$("pagePresetLabel").textContent=`${currentNovel.page.preset} ${currentNovel.page.charsPerLine}字×${currentNovel.page.linesPerPage}行`}
function fmt(r){if(!r)return"未設定";const d=new Date(r);return`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`}
function countdown(){if(!currentNovel)return;const labels={early:"早割り",standard:"標準",express:"特急"},box=$("deadlineRow");box.innerHTML="";["early","standard","express"].forEach(k=>{const s=document.createElement("span");s.className=k===currentNovel.activeDeadline?"active":"";s.textContent=`${labels[k]} ${fmt(currentNovel.deadlines?.[k])}`;s.style.cursor="pointer";s.onclick=()=>{currentNovel.activeDeadline=k;scheduleSave();countdown();refreshStats()};box.appendChild(s)});const r=currentNovel.deadlines?.[currentNovel.activeDeadline];if(!r){$("countdown").textContent="締切未設定";return}const diff=new Date(r)-Date.now();if(diff<=0){$("countdown").textContent="締切時刻を過ぎました";return}const d=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);$("countdown").textContent=`${d}日 ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function scheduleSave(){if(!currentNovel)return;flushEditor();$("saveState").textContent="保存中…";$("cloudState").textContent="ローカル保存済み / クラウド待機";clearTimeout(saveTimer);saveTimer=setTimeout(saveAll,1500)}
async function saveAll(){if(!currentNovel)return;try{flushEditor();const b=writeBatch(db);b.set(doc(db,"novels",currentNovel.id),{title:currentNovel.title,targetWords:currentNovel.targetWords,deadlines:currentNovel.deadlines,activeDeadline:currentNovel.activeDeadline,page:currentNovel.page,editorDisplay:currentNovel.editorDisplay,customRules:currentNovel.customRules,updatedAt:serverTimestamp()},{merge:true});chapters.forEach(ch=>b.set(doc(db,"novels",currentNovel.id,"chapters",ch.id),{title:ch.title,order:ch.order,text:ch.text,updatedAt:serverTimestamp()},{merge:true}));await b.commit();const t=new Date().toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit",second:"2-digit"});$("saveState").textContent=`保存済み ${t}`;$("cloudState").textContent=`Firebase同期済み ${t}`}catch{$("saveState").textContent="クラウド保存失敗";$("cloudState").textContent="ローカルには保存済み";toast("Firebaseへの保存に失敗しました。")}}
function refreshActiveDeadlineOptions(){
  const select=$("activeDeadline"), current=select.value||currentNovel?.activeDeadline||"early";select.innerHTML="";
  const keys=["early","standard","express"],dates={early:$("earlyDeadline").value,standard:$("standardDeadline").value,express:$("expressDeadline").value},labels={early:$("earlyDeadlineLabel").value.trim()||"締切1",standard:$("standardDeadlineLabel").value.trim()||"締切2",express:$("expressDeadlineLabel").value.trim()||"締切3"};
  const configured=keys.filter(k=>dates[k]),targets=configured.length?configured:keys;
  targets.forEach(k=>{const o=document.createElement("option");o.value=k;o.textContent=labels[k];select.appendChild(o);});
  select.value=targets.includes(current)?current:targets[0];
}
function openSettings(){const d=currentNovel.deadlines||{};$("earlyDeadline").value=d.early||"";$("standardDeadline").value=d.standard||"";$("expressDeadline").value=d.express||"";$("activeDeadline").value=currentNovel.activeDeadline||"early";$("targetWordsInput").value=currentNovel.targetWords;$("pagePreset").value=currentNovel.page.preset;$("fontSize").value=currentNovel.page.fontSize;$("charsPerLine").value=currentNovel.page.charsPerLine;$("linesPerPage").value=currentNovel.page.linesPerPage;$("realPageMode").checked=currentNovel.page.realPageMode;$("editorFontSize").value=currentNovel.editorDisplay.fontSize;renderRules();$("settingsDialog").showModal()}
function renderRules(){const b=$("customRulesList");b.innerHTML="";currentNovel.customRules.forEach((r,i)=>{const x=document.createElement("div");x.className="rule-item";x.innerHTML='<span></span><button type="button">削除</button>';x.querySelector("span").textContent=`${r.from} → ${r.to||"要確認"}`;x.querySelector("button").onclick=()=>{currentNovel.customRules.splice(i,1);renderRules()};b.appendChild(x)})}
function addRule(){const from=$("ruleFrom").value.trim(),to=$("ruleTo").value.trim();if(!from)return;currentNovel.customRules.push({from,to});$("ruleFrom").value="";$("ruleTo").value="";renderRules()}
function saveSettings(){currentNovel.deadlines={early:$("earlyDeadline").value,standard:$("standardDeadline").value,express:$("expressDeadline").value};currentNovel.activeDeadline=$("activeDeadline").value;currentNovel.targetWords=Number($("targetWordsInput").value)||80000;currentNovel.page={preset:$("pagePreset").value,fontSize:Number($("fontSize").value)||10.5,charsPerLine:Number($("charsPerLine").value)||40,linesPerPage:Number($("linesPerPage").value)||16,realPageMode:$("realPageMode").checked};currentNovel.editorDisplay={fontSize:Number($("editorFontSize").value)||16};$("editor").style.fontSize=`${currentNovel.editorDisplay.fontSize}px`;$("settingsDialog").close();refreshStats();countdown();scheduleSave()}
function esc(s){return s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function proof(){if(proofMode){flushEditor();proofMode=false;$("proofSummary").classList.add("hidden");$("editor").textContent=activeChapter().text;return}flushEditor();let parts=[{text:activeChapter()?.text||"",mark:null}],hits=[];[...defaultRules,...currentNovel.customRules].sort((a,b)=>b.from.length-a.from.length).forEach(r=>{let next=[];parts.forEach(p=>{if(p.mark)return next.push(p);p.text.split(new RegExp(`(${esc(r.from)})`,`g`)).forEach(x=>{if(!x)return;if(x===r.from){hits.push(`${r.from}${r.to?" → "+r.to:""}`);next.push({text:x,mark:"proof-style",note:r.to||"要確認"})}else next.push({text:x,mark:null})})});parts=next});$("editor").innerHTML="";parts.forEach(p=>{if(p.mark){const m=document.createElement("mark");m.className=p.mark;m.textContent=p.text;m.title=p.note;$("editor").appendChild(m)}else $("editor").appendChild(document.createTextNode(p.text))});proofMode=true;$("proofSummary").classList.remove("hidden");$("proofSummary").textContent=hits.length?`校閲候補 ${hits.length}件：${[...new Set(hits)].slice(0,8).join(" / ")}`:"現在のルールでは候補は見つかりませんでした。"}
function buildTxt(){flushEditor();const inc=$("includeHeadings").checked,blank=$("blankBetweenChapters").checked,collapse=$("collapseBlankLines").checked,trim=$("trimLineHeads").checked;return chapters.map(c=>{let t=c.text||"";if(trim)t=t.split(/\r?\n/).map(x=>x.replace(/^[ \t　]+/,"")).join("\n");if(collapse)t=t.replace(/\n{3,}/g,"\n\n");return inc?`${c.title}\n\n${t}`:t}).join(blank?"\n\n":"\n")}
function downloadTxt(){const b=new Blob([buildTxt()],{type:"text/plain;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=`${currentNovel.title}.txt`;a.click();URL.revokeObjectURL(a.href);$("exportDialog").close()}

$("signupBtn").onclick=signup;$("loginBtn").onclick=login;$("logoutBtn").onclick=()=>signOut(auth);$("newNovelBtn").onclick=()=>{$("newNovelDialog").showModal();$("newTitle").value="";$("newReading").value="";$("newSlug").value=""};$("newTitle").addEventListener("input",suggestSlug);$("newReading").addEventListener("input",suggestSlug);$("createNovelBtn").onclick=createNovel;$("backBtn").onclick=async()=>{await saveAll();dashboard()};$("addChapterBtn").onclick=addChapter;$("settingsBtn").onclick=openSettings;$("saveSettingsBtn").onclick=saveSettings;$("addRuleBtn").onclick=addRule;$("pagePreset").onchange=e=>{if(e.target.value==="A6"){$("charsPerLine").value=40;$("linesPerPage").value=16}if(e.target.value==="A5"){$("charsPerLine").value=57;$("linesPerPage").value=23}};$("proofBtn").onclick=proof;$("exportBtn").onclick=()=>$("exportDialog").showModal();$("downloadTxtBtn").onclick=downloadTxt;$("editor").addEventListener("input",()=>{if(proofMode){proofMode=false;$("proofSummary").classList.add("hidden")}flushEditor();refreshStats();scheduleSave()});window.addEventListener("popstate",()=>{const s=routeSlug();if(auth.currentUser&&s)openNovelSlug(s);else if(auth.currentUser)dashboard()});setInterval(countdown,1000);setInterval(refreshStats,30000);
onAuthStateChanged(auth,async u=>{if(!u){currentNovel=null;showView("authView");return}await userLabel(u);const s=routeSlug();if(s)await openNovelSlug(s);else await dashboard()});function updateCountdown(){
  if(!currentNovel)return;
  const keys=["early","standard","express"];
  const configured=keys.filter(k=>currentNovel.deadlines?.[k]);
  $("deadlineRow").innerHTML="";
  if(configured.length && !configured.includes(currentNovel.activeDeadline)) currentNovel.activeDeadline=configured[0];
  configured.forEach(k=>{
    const s=document.createElement("span");s.className=k===currentNovel.activeDeadline?"active":"";
    s.textContent=`${currentNovel.deadlineLabels?.[k]||k} ${formatDeadline(currentNovel.deadlines?.[k])}`;s.style.cursor="pointer";
    s.onclick=()=>{currentNovel.activeDeadline=k;scheduleCloudSave();updateCountdown();refreshStats();};$("deadlineRow").appendChild(s);
  });
  if(!configured.length){$("countdown").textContent="締切未設定";return;}
  const raw=currentNovel.deadlines?.[currentNovel.activeDeadline];
  const diff=new Date(raw).getTime()-Date.now();if(diff<=0){$("countdown").textContent="締切時刻を過ぎました";return;}
  const days=Math.floor(diff/86400000),h=Math.floor(diff%86400000/3600000),m=Math.floor(diff%3600000/60000),s=Math.floor(diff%60000/1000);
  $("countdown").textContent=`${days}日 ${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;
}

